# Generated by Django 3.2.24 on 2024-02-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descrition',
            new_name='description',
        ),
    ]
